twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        site_key: '%env(APP_RECAPTCHA_SITE_KEY)%'
        APP_MAPBOX_KEY: '%env(APP_MAPBOX_KEY)%'
